# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=120)),
                ('status', models.TextField()),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=120, unique=True)),
                ('status', models.TextField()),
                ('r_votes', models.IntegerField(default=3)),
            ],
        ),
    ]
