# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upost',
            name='r_votes',
            field=models.IntegerField(default=1),
        ),
    ]
